package Xokyopo.HW_2.MessageParser;

public enum Tag {
    LOGINTAG, PASSWORDTAG, PRIVATETAG, MESSAGETAG, BLACKLISTTAG, NICKNAMETAG, SERVERCOMANDTAG, ID, CLIENTLISTTAG, SERVERINFOTAG, ERRORTAG, SETNIKNAMETAG
}
