package Xokyopo.hw_6.chat_server.MessageParser;

public enum Tag {
    LOGINTAG, PASSWORDTAG, PRIVATETAG, MESSAGETAG, BLACKLISTTAG, NICKNAMETAG, SERVERCOMANDTAG, ID, CLIENTLISTTAG, SERVERINFOTAG, ERRORTAG, SETNIKNAMETAG
}
